# Generated by Django 3.2.4 on 2021-08-01 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('help_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
